services:
  aspnetcore-api:
    image: ghcr.io/alexey020602/ner-x5/aspnetcore
    pull_policy: always
    environment:
      ASPNETCORE_HTTP_PORTS: "5067"
      
      HuggingFace__ModelRepoName: ${HuggingFace__ModelRepoName}
      HuggingFace__ModelRepoToken: ${HuggingFace__ModelRepoToken}
    ports:
      - "5067:5067"
