[project]
name = "entities-extraction-x5"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "aioredis>=2.0.1",
    "fastapi[standard]>=0.117.1",
]
