    version: '3.8'
    services:
      fastapi_app:
        build: 
          context: .
          dockerfile: DOCKERFILE # Path to your FastAPI application directory
        ports:
          - "8000:8000"