name: Build Application

on:
  workflow_call:
    inputs:
      application:
        type: string
        required: true
        
permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          driver-opts: |
            image=moby/buildkit:buildx-stable-1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase owner name
        run: |
          echo "APP_LC=${APP,,}" >> $GITHUB_ENV
          echo "REPO_LC=${REPO,,}" >> $GITHUB_ENV
        env:
          REPO: ${{ github.repository }}
          APP: ${{ inputs.application }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ inputs.application }}
          file: ${{ inputs.application }}/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.REPO_LC }}/${{ env.APP_LC }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
